# Generated by Django 3.2.16 on 2022-11-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('CLIENT', 'client')], default='client', max_length=20),
        ),
    ]
